version: "3"  
volumes:
  jellyfin-cache:
    driver: local
  jellyfin-config:
    driver: local
services:  
  jellyfin:  
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: "host"  
    user: 114:119
    restart: unless-stopped
    volumes:  
      - 'jellyfin-cache:/config'
      - 'jellyfin-cache:/cache'
      - /srv/dev-disk-by-label-data1/media:/media
#    ports:
#      - 8096:8096
#      - 1900:1900/udp
