version: "3"  
volumes:
  jellyfin-cache:
    driver: local
  jellyfin-config:
    driver: local
services:  
  jellyfin:  
    image: jellyfin/jellyfin
    network_mode: "host"  
#    user: 1000:1000
    volumes:  
      - 'jellyfin-cache:/config'
      - 'jellyfin-cache:/cache'
      - /nas/media:/media
    ports:
      - 8096:8096
#      - 1900:1900/udp

